import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';

interface University {
  name: string;
  website: string;
}

const universities: Record<string, University[]> = {
  'united-kingdom': [
  { name: 'Aberystwyth University', website: 'https://www.aber.ac.uk/' },
  { name: 'Abertay University', website: 'https://www.abertay.ac.uk/' },
  { name: 'Anglia Ruskin University', website: 'https://aru.ac.uk/' },
  { name: 'Aston University', website: 'https://www.aston.ac.uk/' },
  { name: 'Bangor University', website: 'https://www.bangor.ac.uk/' },
  { name: 'Bath Spa University', website: 'https://www.bathspa.ac.uk/' },
  { name: 'Birkbeck, University of London', website: 'http://www.bbk.ac.uk/' },
  { name: 'Birmingham City University', website: 'https://www.bcu.ac.uk/' },
  { name: 'Bishop Grosseteste University', website: 'https://www.bgu.ac.uk/' },
  { name: 'Bournemouth University', website: 'https://www.bournemouth.ac.uk/' },
  { name: 'Brunel University London', website: 'https://www.brunel.ac.uk/' },
  { name: 'Buckinghamshire New University', website: 'https://www.bucks.ac.uk/' },
  { name: 'Canterbury Christ Church University', website: 'https://www.canterbury.ac.uk/' },
  { name: 'Cardiff Metropolitan University', website: 'https://www.cardiffmet.ac.uk/' },
  { name: 'Cardiff University', website: 'https://www.cardiff.ac.uk/' },
  { name: 'City, University of London', website: 'https://www.city.ac.uk/' },
  { name: 'Coventry University', website: 'https://www.coventry.ac.uk/' },
  { name: 'Cranfield University', website: 'https://www.cranfield.ac.uk/' },
  { name: 'De Montfort University', website: 'https://www.dmu.ac.uk/' },
  { name: 'Durham University', website: 'https://www.dur.ac.uk/' },
  { name: 'Edge Hill University', website: 'https://www.edgehill.ac.uk/' },
  { name: 'Edinburgh Napier University', website: 'https://www.napier.ac.uk/' },
  { name: 'Falmouth University', website: 'https://www.falmouth.ac.uk/' },
  { name: 'Glasgow Caledonian University', website: 'https://www.gcu.ac.uk/' },
  { name: 'Goldsmiths, University of London', website: 'https://www.gold.ac.uk/' },
  { name: 'Harper Adams University', website: 'https://www.harper-adams.ac.uk/' },
  { name: 'Heriot-Watt University', website: 'https://www.hw.ac.uk/' },
  { name: 'Imperial College London', website: 'https://www.imperial.ac.uk/' },
  { name: 'Keele University', website: 'https://www.keele.ac.uk/' },
  { name: 'King’s College London', website: 'https://www.kcl.ac.uk/' },
  { name: 'Kingston University', website: 'https://www.kingston.ac.uk/' },
  { name: 'Lancaster University', website: 'https://www.lancaster.ac.uk/' },
  { name: 'Leeds Beckett University', website: 'https://www.leedsbeckett.ac.uk/' },
  { name: 'Leeds Trinity University', website: 'https://www.leedstrinity.ac.uk/' },
  { name: 'Liverpool Hope University', website: 'https://www.hope.ac.uk/' },
  { name: 'Liverpool John Moores University', website: 'https://www.ljmu.ac.uk/' },
  { name: 'London Metropolitan University', website: 'https://www.londonmet.ac.uk/' },
  { name: 'London School of Economics and Political Science (LSE)', website: 'https://www.lse.ac.uk/' },
  { name: 'London South Bank University', website: 'https://www.lsbu.ac.uk/' },
  { name: 'Loughborough University', website: 'https://www.lboro.ac.uk/' },
  { name: 'Manchester Metropolitan University', website: 'https://www.mmu.ac.uk/' },
  { name: 'Middlesex University', website: 'https://www.mdx.ac.uk/' },
  { name: 'Newcastle University', website: 'https://www.ncl.ac.uk/' },
  { name: 'Northumbria University', website: 'https://www.northumbria.ac.uk/' },
  { name: 'Nottingham Trent University', website: 'https://www.ntu.ac.uk/' },
  { name: 'Open University', website: 'http://www.open.ac.uk/' },
  { name: 'Oxford Brookes University', website: 'https://www.brookes.ac.uk/' },
  { name: 'Queen Mary University of London', website: 'https://www.qmul.ac.uk/' },
  { name: 'Queen’s University Belfast', website: 'https://www.qub.ac.uk/' },
  { name: 'Robert Gordon University', website: 'https://www.rgu.ac.uk/' },
  { name: 'Royal Holloway, University of London', website: 'https://www.royalholloway.ac.uk/' },
  { name: 'Sheffield Hallam University', website: 'https://www.shu.ac.uk/' },
  { name: 'SOAS University of London', website: 'https://www.soas.ac.uk/' },
  { name: 'Solent University', website: 'https://www.solent.ac.uk/' },
  { name: 'Swansea University', website: 'https://www.swansea.ac.uk/' },
  { name: 'Teesside University', website: 'https://www.tees.ac.uk/' },
  { name: 'Ulster University', website: 'https://www.ulster.ac.uk/' },
  { name: 'University College London (UCL)', website: 'https://www.ucl.ac.uk/' },
  { name: 'University for the Creative Arts', website: 'https://www.uca.ac.uk/' },
  { name: 'University of Aberdeen', website: 'https://www.abdn.ac.uk/' },
  { name: 'University of Bath', website: 'https://www.bath.ac.uk/' },
  { name: 'University of Bedfordshire', website: 'https://www.beds.ac.uk/' },
  { name: 'University of Birmingham', website: 'https://www.birmingham.ac.uk/' },
  { name: 'University of Bolton', website: 'https://www.bolton.ac.uk/' },
  { name: 'University of Bradford', website: 'https://www.bradford.ac.uk/' },
  { name: 'University of Brighton', website: 'https://www.brighton.ac.uk/' },
  { name: 'University of Bristol', website: 'https://www.bristol.ac.uk/' },
  { name: 'University of Buckingham', website: 'https://www.buckingham.ac.uk/' },
  { name: 'University of Cambridge', website: 'https://www.cam.ac.uk/' },
  { name: 'University of Central Lancashire', website: 'https://www.uclan.ac.uk/' },
  { name: 'University of Chester', website: 'https://www1.chester.ac.uk/' },
  { name: 'University of Chichester', website: 'https://www.chi.ac.uk/' },
  { name: 'University of Cumbria', website: 'https://www.cumbria.ac.uk/' },
  { name: 'University of Derby', website: 'https://www.derby.ac.uk/' },
  { name: 'University of Dundee', website: 'https://www.dundee.ac.uk/' },
  { name: 'University of East Anglia', website: 'https://www.uea.ac.uk/' },
  { name: 'University of East London', website: 'https://www.uel.ac.uk/' },
  { name: 'University of Edinburgh', website: 'https://www.ed.ac.uk/' },
  { name: 'University of Essex', website: 'https://www.essex.ac.uk/' },
  { name: 'University of Exeter', website: 'https://www.exeter.ac.uk/' },
  { name: 'University of Glasgow', website: 'https://www.gla.ac.uk/' },
  { name: 'University of Gloucestershire', website: 'https://www.glos.ac.uk/' },
  { name: 'University of Greenwich', website: 'https://www.gre.ac.uk/' },
  { name: 'University of Hertfordshire', website: 'https://www.herts.ac.uk/' },
  { name: 'University of Huddersfield', website: 'https://www.hud.ac.uk/' },
  { name: 'University of Hull', website: 'https://www.hull.ac.uk/' },
  { name: 'University of Kent', website: 'https://www.kent.ac.uk/' },
  { name: 'University of Law', website: 'https://www.law.ac.uk/' },
  { name: 'University of Leeds', website: 'https://www.leeds.ac.uk/' },
  { name: 'University of Leicester', website: 'https://le.ac.uk/' },
  { name: 'University of Lincoln', website: 'https://www.lincoln.ac.uk/' },
  { name: 'University of Liverpool', website: 'https://www.liverpool.ac.uk/' },
  { name: 'University of London', website: 'https://london.ac.uk/' },
  { name: 'University of Manchester', website: 'https://www.manchester.ac.uk/' },
  { name: 'University of Northampton', website: 'https://www.northampton.ac.uk/' },
  { name: 'University of Nottingham', website: 'https://www.nottingham.ac.uk/' },
  { name: 'University of Oxford', website: 'https://www.ox.ac.uk/' },
  { name: 'University of Plymouth', website: 'https://www.plymouth.ac.uk/' },
  { name: 'University of Portsmouth', website: 'https://www.port.ac.uk/' },
  { name: 'University of Reading', website: 'https://www.reading.ac.uk/' },
  { name: 'University of Roehampton', website: 'https://www.roehampton.ac.uk/' },
  { name: 'University of Salford', website: 'https://www.salford.ac.uk/' },
  { name: 'University of Sheffield', website: 'https://www.sheffield.ac.uk/' },
  { name: 'University of Southampton', website: 'https://www.southampton.ac.uk/' },
  { name: 'University of St Andrews', website: 'https://www.st-andrews.ac.uk/' },
  { name: 'University of Stirling', website: 'https://www.stir.ac.uk/' },
  { name: 'University of Strathclyde', website: 'https://www.strath.ac.uk/' },
  { name: 'University of Suffolk', website: 'https://www.uos.ac.uk/' },
  { name: 'University of Sunderland', website: 'https://www.sunderland.ac.uk/' },
  { name: 'University of Surrey', website: 'https://www.surrey.ac.uk/' },
  { name: 'University of Sussex', website: 'https://www.sussex.ac.uk/' },
  { name: 'University of Wales Trinity Saint David', website: 'https://www.uwtsd.ac.uk/' },
  { name: 'University of Warwick', website: 'https://warwick.ac.uk/' },
  { name: 'University of West London', website: 'https://www.uwl.ac.uk/' },
  { name: 'University of Westminster', website: 'https://www.westminster.ac.uk/' },
  { name: 'University of Winchester', website: 'https://www.winchester.ac.uk/' },
  { name: 'University of Wolverhampton', website: 'https://www.wlv.ac.uk/' },
  { name: 'University of Worcester', website: 'https://www.worcester.ac.uk/' },
  { name: 'York St John University', website: 'https://www.yorksj.ac.uk/' },
],
 'united-states': [
  { name: 'Adams State University', website: 'https://www.adams.edu/' },
  { name: 'Adelphi University', website: 'https://www.adelphi.edu/' },
  { name: 'Adrian College', website: 'https://www.adrian.edu/' },
  { name: 'Agnes Scott College', website: 'https://www.agnesscott.edu/' },
  { name: 'Air Force Institute of Technology', website: 'https://www.afit.edu/' },
  { name: 'Alabama A&M University', website: 'https://www.aamu.edu/' },
  { name: 'Alabama State University', website: 'https://www.alasu.edu/' },
  { name: 'Alaska Bible College', website: 'https://www.akbible.edu/' },
  { name: 'Alaska Pacific University', website: 'https://www.alaskapacific.edu/' },
  { name: 'Albany College of Pharmacy and Health Sciences', website: 'https://www.acphs.edu/' },
  { name: 'Albany Law School', website: 'https://www.albanylaw.edu/' },
  { name: 'Albany Medical College', website: 'https://www.amc.edu/' },
  { name: 'Albany State University', website: 'https://www.asurams.edu/' },
  { name: 'Albertus Magnus College', website: 'https://www.albertus.edu/' },
  { name: 'Albion College', website: 'https://www.albion.edu/' },
  { name: 'Albright College', website: 'https://www.albright.edu/' },
  { name: 'Alcorn State University', website: 'https://www.alcorn.edu/' },
  { name: 'Alderson Broaddus University', website: 'https://ab.edu/' },
  { name: 'Alfred State College', website: 'https://www.alfredstate.edu/' },
  { name: 'Alfred University', website: 'https://www.alfred.edu/' },
  { name: 'Alice Lloyd College', website: 'https://www.alc.edu/' },
  { name: 'Allegheny College', website: 'https://allegheny.edu/' },
  { name: 'Allen College', website: 'https://www.allencollege.edu/' },
  { name: 'Allen University', website: 'https://www.allenuniversity.edu/' },
  { name: 'Alliant International University', website: 'https://www.alliant.edu/' },
  { name: 'Alma College', website: 'https://www.alma.edu/' },
  { name: 'Alvernia University', website: 'https://www.alvernia.edu/' },
  { name: 'Alverno College', website: 'https://www.alverno.edu/' },
  { name: 'Amberton University', website: 'https://www.amberton.edu/' },
  { name: 'American Baptist College', website: 'https://abcnash.edu/' },
  { name: 'American Film Institute Conservatory', website: 'https://conservatory.afi.com/' },
  { name: 'American International College', website: 'https://www.aic.edu/' },
  { name: 'American Jewish University', website: 'https://www.aju.edu/' },
  { name: 'American University', website: 'https://www.american.edu/' },
  { name: 'Amherst College', website: 'https://www.amherst.edu/' },
  { name: 'Anderson University', website: 'https://anderson.edu/' },
  { name: 'Andrews University', website: 'https://www.andrews.edu/' },
  { name: 'Angelo State University', website: 'https://www.angelo.edu/' },
  { name: 'Anna Maria College', website: 'https://www.annamaria.edu/' },
  { name: 'Antioch University', website: 'https://www.antioch.edu/' },
  { name: 'Appalachian State University', website: 'https://www.appstate.edu/' },
  { name: 'Aquinas College', website: 'https://www.aquinas.edu/' },
  { name: 'Arcadia University', website: 'https://www.arcadia.edu/' },
  { name: 'Arizona Christian University', website: 'https://www.arizonachristian.edu/' },
  { name: 'Arizona State University', website: 'https://www.asu.edu/' },
  { name: 'Arkansas Baptist College', website: 'https://www.arkansasbaptist.edu/' },
  { name: 'Arkansas State University', website: 'https://www.astate.edu/' },
  { name: 'Arkansas Tech University', website: 'https://www.atu.edu/' },
  { name: 'Art Academy of Cincinnati', website: 'https://www.artacademy.edu/' },
  { name: 'ArtCenter College of Design', website: 'https://www.artcenter.edu/' },
  { name: 'Asbury University', website: 'https://www.asbury.edu/' },
  { name: 'Ashland University', website: 'https://www.ashland.edu/' },
  { name: 'Assumption College', website: 'https://www.assumption.edu/' },
  { name: 'Auburn University', website: 'https://www.auburn.edu/' },
  { name: 'Auburn University at Montgomery', website: 'https://www.aum.edu/' },
  { name: 'Augsburg University', website: 'https://www.augsburg.edu/' },
  { name: 'Augusta University', website: 'https://www.augusta.edu/' },
  { name: 'Augustana College', website: 'https://www.augustana.edu/' },
  { name: 'Augustana University', website: 'https://www.augie.edu/' },
  { name: 'Aurora University', website: 'https://aurora.edu/' },
  { name: 'Austin College', website: 'https://www.austincollege.edu/' },
  { name: 'Austin Peay State University', website: 'https://www.apsu.edu/' },
  { name: 'Ave Maria University', website: 'https://www.avemaria.edu/' },
  { name: 'Averett University', website: 'https://www.averett.edu/' },
  { name: 'Avila University', website: 'https://www.avila.edu/' },
  { name: 'Azusa Pacific University', website: 'https://www.apu.edu/' },
  { name: 'Babson College', website: 'https://www.babson.edu/' },
  { name: 'Bacone College', website: 'https://www.bacone.edu/' },
  { name: 'Baker College', website: 'https://www.baker.edu/' },
  { name: 'Baker University', website: 'https://www.bakeru.edu/' },
  { name: 'Baldwin Wallace University', website: 'https://www.bw.edu/' },
  { name: 'Ball State University', website: 'https://www.bsu.edu/' },
  { name: 'Bard College', website: 'https://www.bard.edu/' },
  { name: 'Barnard College', website: 'https://barnard.edu/' },
  { name: 'Barry University', website: 'https://www.barry.edu/' },
  { name: 'Barton College', website: 'https://www.barton.edu/' },
  { name: 'Bastyr University', website: 'https://bastyr.edu/' },
  { name: 'Bates College', website: 'https://www.bates.edu/' },
  { name: 'Baylor University', website: 'https://www.baylor.edu/' },
  { name: 'Beacon College', website: 'https://www.beaconcollege.edu/' },
  { name: 'Belmont Abbey College', website: 'https://belmontabbeycollege.edu/' },
  { name: 'Belmont University', website: 'https://www.belmont.edu/' },
  { name: 'Beloit College', website: 'https://www.beloit.edu/' },
  { name: 'Bemidji State University', website: 'https://www.bemidjistate.edu/' },
  { name: 'Benedict College', website: 'https://www.benedict.edu/' },
  { name: 'Benedictine College', website: 'https://www.benedictine.edu/' },
  { name: 'Benedictine University', website: 'https://www.ben.edu/' },
  { name: 'Bennington College', website: 'https://www.bennington.edu/' },
  { name: 'Bentley University', website: 'https://www.bentley.edu/' },
  { name: 'Berea College', website: 'https://www.berea.edu/' },
  { name: 'Berkeley College', website: 'https://www.berkeleycollege.edu/' },
  { name: 'Berry College', website: 'https://www.berry.edu/' },
  { name: 'Bethany College', website: 'https://www.bethanywv.edu/' },
  { name: 'Bethel College', website: 'https://www.bethelks.edu/' },
  { name: 'Bethel University', website: 'https://www.bethel.edu/' },
  { name: 'Biola University', website: 'https://www.biola.edu/' },
  { name: 'Birmingham-Southern College', website: 'https://www.bsc.edu/' },
  { name: 'Black Hills State University', website: 'https://www.bhsu.edu/' },
  { name: 'Bloomfield College', website: 'https://bloomfield.edu/' },
  { name: 'Bloomsburg University of Pennsylvania', website: 'https://www.bloomu.edu/' },
  { name: 'Blue Mountain College', website: 'https://bmc.edu/' },
  { name: 'Bluefield College', website: 'https://www.bluefield.edu/' },
  { name: 'Bluefield State College', website: 'https://bluefieldstate.edu/' },
  { name: 'Boise State University', website: 'https://www.boisestate.edu/' },
  { name: 'Boston College', website: 'https://www.bc.edu/' },
  { name: 'Boston University', website: 'https://www.bu.edu/' },
  { name: 'Bowdoin College', website: 'https://www.bowdoin.edu/' },
  { name: 'Bowie State University', website: 'https://www.bowiestate.edu/' },
  { name: 'Bowling Green State University', website: 'https://www.bgsu.edu/' },
  { name: 'Bradley University', website: 'https://www.bradley.edu/' },
  { name: 'Brandeis University', website: 'https://www.brandeis.edu/' },
  { name: 'Brenau University', website: 'https://www.brenau.edu/' },
  { name: 'Briar Cliff University', website: 'https://www.briarcliff.edu/' },
  { name: 'Bridgewater College', website: 'https://www.bridgewater.edu/' },
  { name: 'Bridgewater State University', website: 'https://www.bridgew.edu/' },
  { name: 'Brigham Young University', website: 'https://www.byu.edu/' },
  { name: 'Brooklyn College', website: 'https://www.brooklyn.cuny.edu/' },
  { name: 'Brown University', website: 'https://www.brown.edu/' },
  { name: 'Bryant University', website: 'https://www.bryant.edu/' },
  { name: 'Bryn Athyn College', website: 'https://brynathyn.edu/' },
  { name: 'Bryn Mawr College', website: 'https://www.brynmawr.edu/' },
  { name: 'Bucknell University', website: 'https://www.bucknell.edu/' },
  { name: 'Buena Vista University', website: 'https://www.bvu.edu/' },
  { name: 'Butler University', website: 'https://www.butler.edu/' },
  { name: 'California Baptist University', website: 'https://calbaptist.edu/' },
  { name: 'California College of the Arts', website: 'https://www.cca.edu/' },
  { name: 'California Institute of Technology', website: 'https://www.caltech.edu/' },
  { name: 'California Lutheran University', website: 'https://www.callutheran.edu/' },
  { name: 'California Polytechnic State University', website: 'https://www.calpoly.edu/' },
  { name: 'California State University', website: 'https://www.calstate.edu/' },
  { name: 'Calvin University', website: 'https://calvin.edu/' },
  { name: 'Cambridge College', website: 'https://www.cambridgecollege.edu/' },
  { name: 'Canisius College', website: 'https://www.canisius.edu/' },
  { name: 'Capella University', website: 'https://www.capella.edu/' },
  { name: 'Capital University', website: 'https://www.capital.edu/' },
  { name: 'Carleton College', website: 'https://www.carleton.edu/' },
  { name: 'Carnegie Mellon University', website: 'https://www.cmu.edu/' },
  { name: 'Carroll College', website: 'https://www.carroll.edu/' },
  { name: 'Carroll University', website: 'https://www.carrollu.edu/' },
  { name: 'Carson-Newman University', website: 'https://www.cn.edu/' },
  { name: 'Carthage College', website: 'https://www.carthage.edu/' },
  { name: 'Case Western Reserve University', website: 'https://case.edu/' },
  { name: 'Castleton University', website: 'https://www.castleton.edu/' },
  { name: 'Catawba College', website: 'https://catawba.edu/' },
  { name: 'Catholic University of America', website: 'https://www.catholic.edu/' },
  { name: 'Cedar Crest College', website: 'https://cedarcrest.edu/' },
  { name: 'Cedarville University', website: 'https://www.cedarville.edu/' },
  { name: 'Centenary College of Louisiana', website: 'https://www.centenary.edu/' },
  { name: 'Centenary University', website: 'https://www.centenaryuniversity.edu/' },
  { name: 'Central College', website: 'https://www.central.edu/' },
  { name: 'Central Connecticut State University', website: 'https://www.ccsu.edu/' },
  { name: 'Central Michigan University', website: 'https://www.cmich.edu/' },
  { name: 'Central State University', website: 'https://www.centralstate.edu/' },
  { name: 'Central Washington University', website: 'https://www.cwu.edu/' },
  { name: 'Centre College', website: 'https://centre.edu/' },
  { name: 'Chadron State College', website: 'https://www.csc.edu/' },
  { name: 'Chaminade University of Honolulu', website: 'https://www.chaminade.edu/' },
  { name: 'Champlain College', website: 'https://www.champlain.edu/' },
  { name: 'Chapman University', website: 'https://www.chapman.edu/' },
  { name: 'Charleston Southern University', website: 'https://www.charlestonsouthern.edu/' },
  { name: 'Chatham University', website: 'https://www.chatham.edu/' },
  { name: 'Chestnut Hill College', website: 'https://www.chc.edu/' },
  { name: 'Cheyney University of Pennsylvania', website: 'https://www.cheyney.edu/' },
  { name: 'Christian Brothers University', website: 'https://www.cbu.edu/' },
  { name: 'Christopher Newport University', website: 'https://cnu.edu/' },
  { name: 'City College of New York', website: 'https://www.ccny.cuny.edu/' },
  { name: 'Claflin University', website: 'https://www.claflin.edu/' },
  { name: 'Claremont Graduate University', website: 'https://www.cgu.edu/' },
  { name: 'Claremont McKenna College', website: 'https://www.cmc.edu/' },
  { name: 'Clarion University', website: 'https://www.clarion.edu/' },
  { name: 'Clark Atlanta University', website: 'https://www.cau.edu/' },
  { name: 'Clark University', website: 'https://www.clarku.edu/' },
  { name: 'Clarke University', website: 'https://www.clarke.edu/' },
  { name: 'Clarkson University', website: 'https://www.clarkson.edu/' },
  { name: 'Clayton State University', website: 'https://www.clayton.edu/' },
  { name: 'Clemson University', website: 'https://www.clemson.edu/' },
  { name: 'Cleveland State University', website: 'https://www.csuohio.edu/' },
  { name: 'Coastal Carolina University', website: 'https://www.coastal.edu/' },
  { name: 'Coe College', website: 'https://www.coe.edu/' },
  { name: 'Coker University', website: 'https://www.coker.edu/' },
  { name: 'Colby College', website: 'https://www.colby.edu/' },
  { name: 'Colby-Sawyer College', website: 'https://colby-sawyer.edu/' },
  { name: 'Colgate University', website: 'https://www.colgate.edu/' },
  { name: 'College for Creative Studies', website: 'https://www.collegeforcreativestudies.edu/' },
  { name: 'College of Charleston', website: 'https://www.cofc.edu/' },
  { name: 'College of Mount Saint Vincent', website: 'https://www.mountsaintvincent.edu/' },
  { name: 'College of New Jersey', website: 'https://tcnj.edu/' },
  { name: 'College of Saint Benedict and Saint John’s University', website: 'https://www.csbsju.edu/' },
  { name: 'College of Saint Rose', website: 'https://www.strose.edu/' },
  { name: 'College of Southern Nevada', website: 'https://www.csn.edu/' },
  { name: 'College of William & Mary', website: 'https://www.wm.edu/' },
  { name: 'Colorado Christian University', website: 'https://www.ccu.edu/' },
  { name: 'Colorado College', website: 'https://www.coloradocollege.edu/' },
  { name: 'Colorado Mesa University', website: 'https://www.coloradomesa.edu/' },
  { name: 'Colorado School of Mines', website: 'https://www.mines.edu/' },
  { name: 'Colorado State University', website: 'https://www.colostate.edu/' },
  { name: 'Columbia College Chicago', website: 'https://www.colum.edu/' },
  { name: 'Columbia International University', website: 'https://www.ciu.edu/' },
  { name: 'Columbia University', website: 'https://www.columbia.edu/' },
  { name: 'Concord University', website: 'https://www.concord.edu/' },
  { name: 'Concordia College', website: 'https://www.concordiacollege.edu/' },
  { name: 'Concordia University Chicago', website: 'https://www.cuchicago.edu/' },
  { name: 'Concordia University Irvine', website: 'https://www.cui.edu/' },
  { name: 'Concordia University Saint Paul', website: 'https://www.csp.edu/' },
  { name: 'Concordia University Texas', website: 'https://www.concordia.edu/' },
  { name: 'Concordia University Wisconsin', website: 'https://www.cuw.edu/' },
  { name: 'Connecticut College', website: 'https://www.conncoll.edu/' },
  { name: 'Cornell College', website: 'https://www.cornellcollege.edu/' },
  { name: 'Cornell University', website: 'https://www.cornell.edu/' },
  { name: 'Creighton University', website: 'https://www.creighton.edu/' },
  { name: 'Crown College', website: 'https://www.crown.edu/' },
  { name: 'Culver-Stockton College', website: 'https://www.culver.edu/' },
  { name: 'Cumberland University', website: 'https://www.cumberland.edu/' },
  { name: 'CUNY Graduate Center', website: 'https://www.gc.cuny.edu/' },
  { name: 'CUNY Hunter College', website: 'https://hunter.cuny.edu/' },
  { name: 'CUNY John Jay College of Criminal Justice', website: 'https://www.jjay.cuny.edu/' },
  { name: 'Curry College', website: 'https://www.curry.edu/' },
  { name: 'Daemen University', website: 'https://www.daemen.edu/' },
  { name: 'Dakota State University', website: 'https://www.dsu.edu/' },
  { name: 'Dakota Wesleyan University', website: 'https://www.dwu.edu/' },
  { name: 'Dartmouth College', website: 'https://home.dartmouth.edu/' },
  { name: 'Davidson College', website: 'https://www.davidson.edu/' },
  { name: 'Davis & Elkins College', website: 'https://www.dewv.edu/' },
  { name: 'Dean College', website: 'https://www.dean.edu/' },
  { name: 'Defiance College', website: 'https://www.defiance.edu/' },
  { name: 'Delaware State University', website: 'https://www.desu.edu/' },
  { name: 'Delaware Valley University', website: 'https://www.delval.edu/' },
  { name: 'Denison University', website: 'https://denison.edu/' },
  { name: 'DePaul University', website: 'https://www.depaul.edu/' },
  { name: 'DePauw University', website: 'https://www.depauw.edu/' },
  { name: 'Dickinson College', website: 'https://www.dickinson.edu/' },
  { name: 'Dickinson State University', website: 'https://www.dickinsonstate.edu/' },
  { name: 'Dillard University', website: 'https://www.dillard.edu/' },
  { name: 'Dominican College', website: 'https://www.dc.edu/' },
  { name: 'Dominican University', website: 'https://www.dom.edu/' },
  { name: 'Dominican University of California', website: 'https://www.dominican.edu/' },
  { name: 'Drake University', website: 'https://www.drake.edu/' },
  { name: 'Drew University', website: 'https://www.drew.edu/' },
  { name: 'Drexel University', website: 'https://drexel.edu/' },
  { name: 'Drury University', website: 'https://www.drury.edu/' },
  { name: 'Duke University', website: 'https://www.duke.edu/' },
  { name: 'Duquesne University', website: 'https://www.duq.edu/' },
  { name: 'Earlham College', website: 'https://earlham.edu/' },
  { name: 'East Carolina University', website: 'https://www.ecu.edu/' },
  { name: 'East Central University', website: 'https://www.ecok.edu/' },
  { name: 'East Stroudsburg University', website: 'https://www.esu.edu/' },
  { name: 'East Tennessee State University', website: 'https://www.etsu.edu/' },
  { name: 'Eastern Connecticut State University', website: 'https://www.easternct.edu/' },
  { name: 'Eastern Illinois University', website: 'https://www.eiu.edu/' },
  { name: 'Eastern Kentucky University', website: 'https://www.eku.edu/' },
  { name: 'Eastern Mennonite University', website: 'https://emu.edu/' },
  { name: 'Eastern Michigan University', website: 'https://www.emich.edu/' },
  { name: 'Eastern Nazarene College', website: 'https://www.enc.edu/' },
  { name: 'Eastern Oregon University', website: 'https://www.eou.edu/' },
  { name: 'Eastern University', website: 'https://www.eastern.edu/' },
  { name: 'Eastern Washington University', website: 'https://www.ewu.edu/' },
  { name: 'Edgewood College', website: 'https://www.edgewood.edu/' },
  { name: 'Elizabethtown College', website: 'https://www.etown.edu/' },
  { name: 'Elmhurst University', website: 'https://www.elmhurst.edu/' },
  { name: 'Elon University', website: 'https://www.elon.edu/' },
  { name: 'Embry-Riddle Aeronautical University', website: 'https://www.erau.edu/' },
  { name: 'Emerson College', website: 'https://www.emerson.edu/' },
  { name: 'Emmanuel College', website: 'https://www.emmanuel.edu/' },
  { name: 'Emory & Henry College', website: 'https://www.ehc.edu/' },
  { name: 'Emory University', website: 'https://www.emory.edu/' },
  { name: 'Emporia State University', website: 'https://www.emporia.edu/' },
  { name: 'Endicott College', website: 'https://www.endicott.edu/' },
  { name: 'Erskine College', website: 'https://www.erskine.edu/' },
  { name: 'Eureka College', website: 'https://eureka.edu/' },
  { name: 'Evangel University', website: 'https://www.evangel.edu/' },
  { name: 'Fairfield University', website: 'https://www.fairfield.edu/' },
  { name: 'Fairleigh Dickinson University', website: 'https://www.fdu.edu/' },
  { name: 'Fayetteville State University', website: 'https://www.uncfsu.edu/' },
  { name: 'Felician University', website: 'https://www.felician.edu/' },
  { name: 'Ferris State University', website: 'https://www.ferris.edu/' },
  { name: 'Ferrum College', website: 'https://www.ferrum.edu/' },
  { name: 'Flagler College', website: 'https://www.flagler.edu/' },
  { name: 'Florida Atlantic University', website: 'https://www.fau.edu/' },
  { name: 'Florida College', website: 'https://www.floridacollege.edu/' },
  { name: 'Florida Gulf Coast University', website: 'https://www.fgcu.edu/' },
  { name: 'Florida Institute of Technology', website: 'https://www.fit.edu/' },
  { name: 'Florida International University', website: 'https://www.fiu.edu/' },
  { name: 'Florida Memorial University', website: 'https://www.fmuniv.edu/' },
  { name: 'Florida Southern College', website: 'https://www.flsouthern.edu/' },
  { name: 'Florida State University', website: 'https://www.fsu.edu/' },
  { name: 'Fontbonne University', website: 'https://www.fontbonne.edu/' },
  { name: 'Fordham University', website: 'https://www.fordham.edu/' },
  { name: 'Fort Hays State University', website: 'https://www.fhsu.edu/' },
  { name: 'Fort Lewis College', website: 'https://www.fortlewis.edu/' },
  { name: 'Francis Marion University', website: 'https://www.fmarion.edu/' },
  { name: 'Franciscan University of Steubenville', website: 'https://www.franciscan.edu/' },
  { name: 'Franklin College', website: 'https://franklincollege.edu/' },
  { name: 'Franklin Pierce University', website: 'https://franklinpierce.edu/' },
  { name: 'Franklin University', website: 'https://www.franklin.edu/' },
  { name: 'Franklin W. Olin College of Engineering', website: 'https://www.olin.edu/' },
  { name: 'Frostburg State University', website: 'https://www.frostburg.edu/' },
  { name: 'Furman University', website: 'https://www.furman.edu/' },
  { name: 'Gallaudet University', website: 'https://www.gallaudet.edu/' },
  { name: 'Gannon University', website: 'https://www.gannon.edu/' },
  { name: 'Gardner-Webb University', website: 'https://gardner-webb.edu/' },
  { name: 'Geneva College', website: 'https://www.geneva.edu/' },
  { name: 'George Fox University', website: 'https://www.georgefox.edu/' },
  { name: 'George Mason University', website: 'https://www.gmu.edu/' },
  { name: 'Georgetown University', website: 'https://www.georgetown.edu/' },
  { name: 'Georgia College & State University', website: 'https://www.gcsu.edu/' },
  { name: 'Georgia Institute of Technology', website: 'https://www.gatech.edu/' },
  { name: 'Georgia Southern University', website: 'https://www.georgiasouthern.edu/' },
  { name: 'Georgia State University', website: 'https://www.gsu.edu/' },
  { name: 'Gettysburg College', website: 'https://www.gettysburg.edu/' },
  { name: 'Glenville State University', website: 'https://www.glenville.edu/' },
  { name: 'Goddard College', website: 'https://www.goddard.edu/' },
  { name: 'Gonzaga University', website: 'https://www.gonzaga.edu/' },
  { name: 'Gordon College', website: 'https://www.gordon.edu/' },
  { name: 'Goshen College', website: 'https://www.goshen.edu/' },
  { name: 'Goucher College', website: 'https://www.goucher.edu/' },
  { name: 'Governors State University', website: 'https://www.govst.edu/' },
  { name: 'Grace College & Seminary', website: 'https://www.grace.edu/' },
  { name: 'Graceland University', website: 'https://www.graceland.edu/' },
  { name: 'Grand Canyon University', website: 'https://www.gcu.edu/' },
  { name: 'Grand Valley State University', website: 'https://www.gvsu.edu/' },
  { name: 'Greensboro College', website: 'https://www.greensboro.edu/' },
  { name: 'Greenville University', website: 'https://www.greenville.edu/' },
  { name: 'Grinnell College', website: 'https://www.grinnell.edu/' },
  { name: 'Grove City College', website: 'https://www.gcc.edu/' },
  { name: 'Guilford College', website: 'https://www.guilford.edu/' },
  { name: 'Gustavus Adolphus College', website: 'https://www.gustavus.edu/' },
  { name: 'Gwynedd Mercy University', website: 'https://www.gmercyu.edu/' },

   { name: 'Hamilton College', website: 'https://www.hamilton.edu/' },
  { name: 'Hamline University', website: 'https://www.hamline.edu/' },
  { name: 'Hampden-Sydney College', website: 'https://www.hsc.edu/' },
  { name: 'Hampshire College', website: 'https://www.hampshire.edu/' },
  { name: 'Hampton University', website: 'https://www.hamptonu.edu/' },
  { name: 'Hanover College', website: 'https://www.hanover.edu/' },
  { name: 'Hardin-Simmons University', website: 'https://www.hsutx.edu/' },
  { name: 'Harrisburg University of Science and Technology', website: 'https://www.harrisburgu.edu/' },
  { name: 'Hartwick College', website: 'https://www.hartwick.edu/' },
  { name: 'Harvard University', website: 'https://www.harvard.edu/' },
  { name: 'Harvey Mudd College', website: 'https://www.hmc.edu/' },
  { name: 'Hastings College', website: 'https://www.hastings.edu/' },
  { name: 'Haverford College', website: 'https://www.haverford.edu/' },
  { name: 'Hawaii Pacific University', website: 'https://www.hpu.edu/' },
  { name: 'Heidelberg University', website: 'https://www.heidelberg.edu/' },
  { name: 'Henderson State University', website: 'https://www.hsu.edu/' },
  { name: 'Hendrix College', website: 'https://www.hendrix.edu/' },
  { name: 'High Point University', website: 'https://www.highpoint.edu/' },
  { name: 'Hillsdale College', website: 'https://www.hillsdale.edu/' },
  { name: 'Hiram College', website: 'https://www.hiram.edu/' },
  { name: 'Hobart and William Smith Colleges', website: 'https://www.hws.edu/' },
  { name: 'Hofstra University', website: 'https://www.hofstra.edu/' },
  { name: 'Hollins University', website: 'https://www.hollins.edu/' },
  { name: 'Holy Cross College', website: 'https://www.hcc-nd.edu/' },
  { name: 'Holy Family University', website: 'https://www.holyfamily.edu/' },
  { name: 'Holy Names University', website: 'https://www.hnu.edu/' },
  { name: 'Hope College', website: 'https://hope.edu/' },
  { name: 'Hope International University', website: 'https://www.hiu.edu/' },
  { name: 'Houghton University', website: 'https://www.houghton.edu/' },
  { name: 'Houston Baptist University', website: 'https://www.hbu.edu/' },
  { name: 'Howard Payne University', website: 'https://www.hputx.edu/' },
  { name: 'Howard University', website: 'https://www.howard.edu/' },
  { name: 'Huntingdon College', website: 'https://www.huntingdon.edu/' },
  { name: 'Huntington University', website: 'https://www.huntington.edu/' },
  { name: 'Husson University', website: 'https://www.husson.edu/' },
  { name: 'Illinois College', website: 'https://www.ic.edu/' },
  { name: 'Illinois Institute of Technology', website: 'https://www.iit.edu/' },
  { name: 'Illinois State University', website: 'https://illinoisstate.edu/' },
  { name: 'Illinois Wesleyan University', website: 'https://www.iwu.edu/' },
  { name: 'Immaculata University', website: 'https://www.immaculata.edu/' },
  { name: 'Indiana State University', website: 'https://www.indstate.edu/' },
  { name: 'Indiana University Bloomington', website: 'https://www.indiana.edu/' },
  { name: 'Indiana University of Pennsylvania', website: 'https://www.iup.edu/' },
  { name: 'Indiana Wesleyan University', website: 'https://www.indwes.edu/' },
  { name: 'Iona University', website: 'https://www.iona.edu/' },
  { name: 'Iowa State University', website: 'https://www.iastate.edu/' },
  { name: 'Ithaca College', website: 'https://www.ithaca.edu/' },
  { name: 'Jackson State University', website: 'https://www.jsums.edu/' },
  { name: 'Jacksonville State University', website: 'https://www.jsu.edu/' },
  { name: 'Jacksonville University', website: 'https://www.ju.edu/' },
  { name: 'James Madison University', website: 'https://www.jmu.edu/' },
  { name: 'John Brown University', website: 'https://www.jbu.edu/' },
  { name: 'John Carroll University', website: 'https://www.jcu.edu/' },
  { name: 'Johns Hopkins University', website: 'https://www.jhu.edu/' },
  { name: 'Johnson & Wales University', website: 'https://www.jwu.edu/' },
  { name: 'Johnson C. Smith University', website: 'https://www.jcsu.edu/' },
  { name: 'Juniata College', website: 'https://www.juniata.edu/' },
  { name: 'Kalamazoo College', website: 'https://www.kzoo.edu/' },
  { name: 'Kansas State University', website: 'https://www.k-state.edu/' },
  { name: 'Kean University', website: 'https://www.kean.edu/' },
  { name: 'Keene State College', website: 'https://www.keene.edu/' },
  { name: 'Kent State University', website: 'https://www.kent.edu/' },
  { name: 'Kenyon College', website: 'https://www.kenyon.edu/' },
  { name: 'Kettering University', website: 'https://www.kettering.edu/' },
  { name: 'King University', website: 'https://www.king.edu/' },
  { name: 'King’s College', website: 'https://www.kings.edu/' },
  { name: 'Knox College', website: 'https://www.knox.edu/' },
  { name: 'Kutztown University of Pennsylvania', website: 'https://www.kutztown.edu/' },
  { name: 'La Salle University', website: 'https://www.lasalle.edu/' },
  { name: 'Lafayette College', website: 'https://www.lafayette.edu/' },
  { name: 'Lake Forest College', website: 'https://www.lakeforest.edu/' },
  { name: 'Lake Superior State University', website: 'https://www.lssu.edu/' },
  { name: 'Lamar University', website: 'https://www.lamar.edu/' },
  { name: 'Langston University', website: 'https://www.langston.edu/' },
  { name: 'Lasell University', website: 'https://www.lasell.edu/' },
  { name: 'Lawrence University', website: 'https://www.lawrence.edu/' },
  { name: 'Le Moyne College', website: 'https://www.lemoyne.edu/' },
  { name: 'Lebanon Valley College', website: 'https://www.lvc.edu/' },
  { name: 'Lee University', website: 'https://www.leeuniversity.edu/' },
  { name: 'Lehigh University', website: 'https://www1.lehigh.edu/' },
  { name: 'Lenoir-Rhyne University', website: 'https://www.lr.edu/' },
  { name: 'Lewis & Clark College', website: 'https://www.lclark.edu/' },
  { name: 'Lewis University', website: 'https://www.lewisu.edu/' },
  { name: 'Liberty University', website: 'https://www.liberty.edu/' },
  { name: 'Linfield University', website: 'https://www.linfield.edu/' },
  { name: 'Lipscomb University', website: 'https://www.lipscomb.edu/' },
  { name: 'Lock Haven University', website: 'https://lockhaven.edu/' },
  { name: 'Longwood University', website: 'https://www.longwood.edu/' },
  { name: 'Loras College', website: 'https://www.loras.edu/' },
  { name: 'Louisiana College', website: 'https://www.lacollege.edu/' },
  { name: 'Louisiana State University', website: 'https://www.lsu.edu/' },
  { name: 'Loyola Marymount University', website: 'https://www.lmu.edu/' },
  { name: 'Loyola University Chicago', website: 'https://www.luc.edu/' },
  { name: 'Loyola University Maryland', website: 'https://www.loyola.edu/' },
  { name: 'Loyola University New Orleans', website: 'https://www.loyno.edu/' },
  { name: 'Luther College', website: 'https://www.luther.edu/' },
  { name: 'Lycoming College', website: 'https://www.lycoming.edu/' },
  { name: 'Lynn University', website: 'https://www.lynn.edu/' },
  { name: 'Macalester College', website: 'https://www.macalester.edu/' },
  { name: 'Maharishi International University', website: 'https://www.miu.edu/' },
  { name: 'Manhattan College', website: 'https://manhattan.edu/' },
  { name: 'Manhattan School of Music', website: 'https://www.msmnyc.edu/' },
  { name: 'Manhattanville College', website: 'https://www.mville.edu/' },
  { name: 'Marietta College', website: 'https://www.marietta.edu/' },
  { name: 'Marist College', website: 'https://www.marist.edu/' },
  { name: 'Marquette University', website: 'https://www.marquette.edu/' },
  { name: 'Marshall University', website: 'https://www.marshall.edu/' },
  { name: 'Mary Baldwin University', website: 'https://marybaldwin.edu/' },
  { name: 'Marymount Manhattan College', website: 'https://www.mmm.edu/' },
  { name: 'Marymount University', website: 'https://marymount.edu/' },
  { name: 'Maryville College', website: 'https://www.maryvillecollege.edu/' },
  { name: 'Maryville University', website: 'https://www.maryville.edu/' },
  { name: 'Massachusetts Institute of Technology (MIT)', website: 'https://www.mit.edu/' },
  { name: 'McDaniel College', website: 'https://www.mcdaniel.edu/' },
  { name: 'McKendree University', website: 'https://www.mckendree.edu/' },
  { name: 'McNeese State University', website: 'https://www.mcneese.edu/' },
  { name: 'Mercer University', website: 'https://www.mercer.edu/' },
  { name: 'Mercy College', website: 'https://www.mercy.edu/' },
  { name: 'Mercyhurst University', website: 'https://www.mercyhurst.edu/' },
  { name: 'Merrimack College', website: 'https://www.merrimack.edu/' },
  { name: 'Messiah University', website: 'https://www.messiah.edu/' },
  { name: 'Methodist University', website: 'https://www.methodist.edu/' },
  { name: 'Metropolitan State University', website: 'https://www.metrostate.edu/' },
  { name: 'Metropolitan State University of Denver', website: 'https://www.msudenver.edu/' },
  { name: 'Miami University', website: 'https://www.miamioh.edu/' },
  { name: 'Michigan State University', website: 'https://msu.edu/' },
  { name: 'Michigan Technological University', website: 'https://www.mtu.edu/' },
  { name: 'Middle Tennessee State University', website: 'https://www.mtsu.edu/' },
  { name: 'Middlebury College', website: 'https://www.middlebury.edu/' },
  { name: 'Midwestern State University', website: 'https://msutexas.edu/' },
  { name: 'Millersville University', website: 'https://www.millersville.edu/' },
  { name: 'Millikin University', website: 'https://millikin.edu/' },
  { name: 'Mills College', website: 'https://www.mills.edu/' },
  { name: 'Milwaukee School of Engineering', website: 'https://www.msoe.edu/' },
  { name: 'Minot State University', website: 'https://www.minotstateu.edu/' },
  { name: 'Mississippi College', website: 'https://www.mc.edu/' },
  { name: 'Mississippi State University', website: 'https://www.msstate.edu/' },
  { name: 'Missouri Baptist University', website: 'https://www.mobap.edu/' },
  { name: 'Missouri Southern State University', website: 'https://www.mssu.edu/' },
  { name: 'Missouri State University', website: 'https://www.missouristate.edu/' },
  { name: 'Missouri University of Science and Technology', website: 'https://www.mst.edu/' },
  { name: 'Missouri Western State University', website: 'https://www.missouriwestern.edu/' },
  { name: 'Monmouth College', website: 'https://www.monmouthcollege.edu/' },
  { name: 'Monmouth University', website: 'https://www.monmouth.edu/' },
  { name: 'Montana State University', website: 'https://www.montana.edu/' },
  { name: 'Montana Tech', website: 'https://www.mtech.edu/' },
  { name: 'Montclair State University', website: 'https://www.montclair.edu/' },
  { name: 'Moravian University', website: 'https://www.moravian.edu/' },
  { name: 'Morehead State University', website: 'https://www.moreheadstate.edu/' },
  { name: 'Morehouse College', website: 'https://www.morehouse.edu/' },
  { name: 'Morgan State University', website: 'https://www.morgan.edu/' },
  { name: 'Morningside University', website: 'https://www.morningside.edu/' },
  { name: 'Mount Holyoke College', website: 'https://www.mtholyoke.edu/' },
  { name: 'Mount Mercy University', website: 'https://www.mtmercy.edu/' },
  { name: 'Mount St. Mary’s University', website: 'https://msmary.edu/' },
  { name: 'Muhlenberg College', website: 'https://www.muhlenberg.edu/' },
  { name: 'Murray State University', website: 'https://www.murraystate.edu/' },
  { name: 'Muskingum University', website: 'https://www.muskingum.edu/' },
  { name: 'Naropa University', website: 'https://www.naropa.edu/' },
  { name: 'National Louis University', website: 'https://www.nl.edu/' },
  { name: 'National University', website: 'https://www.nu.edu/' },
  { name: 'Naval Postgraduate School', website: 'https://www.nps.edu/' },
  { name: 'Nazareth College', website: 'https://www2.naz.edu/' },
  { name: 'Nebraska Wesleyan University', website: 'https://www.nebrwesleyan.edu/' },
  { name: 'New England College', website: 'https://www.nec.edu/' },
  { name: 'New England Conservatory of Music', website: 'https://necmusic.edu/' },
  { name: 'New Jersey Institute of Technology', website: 'https://www.njit.edu/' },
  { name: 'New Mexico Highlands University', website: 'https://www.nmhu.edu/' },
  { name: 'New Mexico Institute of Mining and Technology', website: 'https://www.nmt.edu/' },
  { name: 'New Mexico State University', website: 'https://www.nmsu.edu/' },
  { name: 'New York Institute of Technology', website: 'https://www.nyit.edu/' },
  { name: 'New York University', website: 'https://www.nyu.edu/' },
  { name: 'Newberry College', website: 'https://www.newberry.edu/' },
  { name: 'Newman University', website: 'https://newmanu.edu/' },
  { name: 'Niagara University', website: 'https://www.niagara.edu/' },
  { name: 'Nicholls State University', website: 'https://www.nicholls.edu/' },
  { name: 'Norfolk State University', website: 'https://www.nsu.edu/' },
  { name: 'North Carolina A&T State University', website: 'https://www.ncat.edu/' },
  { name: 'North Carolina Central University', website: 'https://www.nccu.edu/' },
  { name: 'North Carolina State University', website: 'https://www.ncsu.edu/' },
  { name: 'North Central College', website: 'https://www.northcentralcollege.edu/' },
  { name: 'North Dakota State University', website: 'https://www.ndsu.edu/' },
  { name: 'North Greenville University', website: 'https://ngu.edu/' },
  { name: 'North Park University', website: 'https://www.northpark.edu/' },
  { name: 'Northeastern State University', website: 'https://www.nsuok.edu/' },
  { name: 'Northeastern University', website: 'https://www.northeastern.edu/' },
  { name: 'Northern Arizona University', website: 'https://www.nau.edu/' },
  { name: 'Northern Illinois University', website: 'https://www.niu.edu/' },
  { name: 'Northern Kentucky University', website: 'https://www.nku.edu/' },
  { name: 'Northern Michigan University', website: 'https://www.nmu.edu/' },
  { name: 'Northern State University', website: 'https://www.northern.edu/' },
  { name: 'Northwest Christian University', website: 'https://www.nwcu.edu/' },
     { name: 'Northwest Missouri State University', website: 'https://www.nwmissouri.edu/' },
  { name: 'Northwest Nazarene University', website: 'https://www.nnu.edu/' },
  { name: 'Northwest University', website: 'https://www.northwestu.edu/' },
  { name: 'Northwestern College', website: 'https://www.nwciowa.edu/' },
  { name: 'Northwestern State University', website: 'https://www.nsula.edu/' },
  { name: 'Northwestern University', website: 'https://www.northwestern.edu/' },
  { name: 'Norwich University', website: 'https://www.norwich.edu/' },
  { name: 'Notre Dame College', website: 'https://www.notredamecollege.edu/' },
  { name: 'Notre Dame de Namur University', website: 'https://www.ndnu.edu/' },
  { name: 'Nova Southeastern University', website: 'https://www.nova.edu/' },
  { name: 'Nyack College', website: 'https://www.nyack.edu/' },
  { name: 'Oberlin College', website: 'https://www.oberlin.edu/' },
  { name: 'Occidental College', website: 'https://www.oxy.edu/' },
  { name: 'Oglethorpe University', website: 'https://oglethorpe.edu/' },
  { name: 'Ohio Dominican University', website: 'https://www.ohiodominican.edu/' },
  { name: 'Ohio Northern University', website: 'https://www.onu.edu/' },
  { name: 'Ohio University', website: 'https://www.ohio.edu/' },
  { name: 'Ohio Wesleyan University', website: 'https://www.owu.edu/' },
  { name: 'Oklahoma Baptist University', website: 'https://www.okbu.edu/' },
  { name: 'Oklahoma Christian University', website: 'https://www.oc.edu/' },
  { name: 'Oklahoma City University', website: 'https://www.okcu.edu/' },
  { name: 'Oklahoma Panhandle State University', website: 'https://www.opsu.edu/' },
  { name: 'Oklahoma State University', website: 'https://go.okstate.edu/' },
  { name: 'Old Dominion University', website: 'https://www.odu.edu/' },
  { name: 'Olivet College', website: 'https://www.olivetcollege.edu/' },
  { name: 'Olivet Nazarene University', website: 'https://www.olivet.edu/' },
  { name: 'Oral Roberts University', website: 'https://oru.edu/' },
  { name: 'Oregon Institute of Technology', website: 'https://www.oit.edu/' },
  { name: 'Oregon State University', website: 'https://oregonstate.edu/' },
  { name: 'Otis College of Art and Design', website: 'https://www.otis.edu/' },
  { name: 'Otterbein University', website: 'https://www.otterbein.edu/' },
  { name: 'Ouachita Baptist University', website: 'https://obu.edu/' },
  { name: 'Our Lady of the Lake University', website: 'https://www.ollusa.edu/' },
  { name: 'Pace University', website: 'https://www.pace.edu/' },
  { name: 'Pacific Lutheran University', website: 'https://www.plu.edu/' },
  { name: 'Pacific University', website: 'https://www.pacificu.edu/' },
  { name: 'Pacific Northwest College of Art', website: 'https://pnca.edu/' },
  { name: 'Palm Beach Atlantic University', website: 'https://www.pba.edu/' },
  { name: 'Park University', website: 'https://www.park.edu/' },
  { name: 'Parsons School of Design', website: 'https://www.newschool.edu/parsons/' },
  { name: 'Pennsylvania College of Technology', website: 'https://www.pct.edu/' },
  { name: 'Pennsylvania State University', website: 'https://www.psu.edu/' },
  { name: 'Pepperdine University', website: 'https://www.pepperdine.edu/' },
  { name: 'Peru State College', website: 'https://www.peru.edu/' },
  { name: 'Pfeiffer University', website: 'https://www.pfeiffer.edu/' },
  { name: 'Philadelphia University', website: 'https://www.philau.edu/' },
  { name: 'Philander Smith College', website: 'https://www.philander.edu/' },
  { name: 'Piedmont College', website: 'https://www.piedmont.edu/' },
  { name: 'Pitzer College', website: 'https://www.pitzer.edu/' },
  { name: 'Platt College', website: 'https://platt.edu/' },
  { name: 'Plymouth State University', website: 'https://www.plymouth.edu/' },
  { name: 'Point Loma Nazarene University', website: 'https://www.pointloma.edu/' },
  { name: 'Point Park University', website: 'https://www.pointpark.edu/' },
  { name: 'Polytechnic University of Puerto Rico', website: 'https://www.pupr.edu/' },
  { name: 'Pomona College', website: 'https://www.pomona.edu/' },
  { name: 'Portland State University', website: 'https://www.pdx.edu/' },
  { name: 'Prairie View A&M University', website: 'https://www.pvamu.edu/' },
  { name: 'Pratt Institute', website: 'https://www.pratt.edu/' },
  { name: 'Presbyterian College', website: 'https://www.presby.edu/' },
  { name: 'Prescott College', website: 'https://www.prescott.edu/' },
  { name: 'Princeton University', website: 'https://www.princeton.edu/' },
  { name: 'Providence College', website: 'https://www.providence.edu/' },
  { name: 'Purdue University', website: 'https://www.purdue.edu/' },
  { name: 'Purdue University Fort Wayne', website: 'https://www.pfw.edu/' },
  { name: 'Purdue University Northwest', website: 'https://www.pnw.edu/' },
  { name: 'Queens University of Charlotte', website: 'https://www.queens.edu/' },
  { name: 'Quincy University', website: 'https://www.quincy.edu/' },
  { name: 'Quinnipiac University', website: 'https://www.qu.edu/' },
  { name: 'Radford University', website: 'https://www.radford.edu/' },
  { name: 'Ramapo College of New Jersey', website: 'https://www.ramapo.edu/' },
  { name: 'Randolph College', website: 'https://www.randolphcollege.edu/' },
  { name: 'Randolph-Macon College', website: 'https://www.rmc.edu/' },
  { name: 'Reed College', website: 'https://www.reed.edu/' },
  { name: 'Regent University', website: 'https://www.regent.edu/' },
  { name: 'Regis College', website: 'https://www.regiscollege.edu/' },
  { name: 'Regis University', website: 'https://www.regis.edu/' },
  { name: 'Rensselaer Polytechnic Institute', website: 'https://www.rpi.edu/' },
  { name: 'Rhode Island College', website: 'https://www.ric.edu/' },
  { name: 'Rhode Island School of Design', website: 'https://www.risd.edu/' },
  { name: 'Rhodes College', website: 'https://www.rhodes.edu/' },
  { name: 'Rice University', website: 'https://www.rice.edu/' },
  { name: 'Rider University', website: 'https://www.rider.edu/' },
  { name: 'Ripon College', website: 'https://www.ripon.edu/' },
  { name: 'Rivier University', website: 'https://www.rivier.edu/' },
  { name: 'Roanoke College', website: 'https://www.roanoke.edu/' },
  { name: 'Robert Morris University', website: 'https://www.rmu.edu/' },
  { name: 'Rochester Institute of Technology', website: 'https://www.rit.edu/' },
  { name: 'Rockford University', website: 'https://www.rockford.edu/' },
  { name: 'Rockhurst University', website: 'https://www.rockhurst.edu/' },
  { name: 'Roger Williams University', website: 'https://www.rwu.edu/' },
  { name: 'Rollins College', website: 'https://www.rollins.edu/' },
  { name: 'Roosevelt University', website: 'https://www.roosevelt.edu/' },
  { name: 'Rose-Hulman Institute of Technology', website: 'https://www.rose-hulman.edu/' },
  { name: 'Rosemont College', website: 'https://www.rosemont.edu/' },
  { name: 'Rowan University', website: 'https://www.rowan.edu/' },
  { name: 'Rutgers University', website: 'https://www.rutgers.edu/' },
   { name: 'Sacred Heart University', website: 'https://www.sacredheart.edu/' },
  { name: 'Saginaw Valley State University', website: 'https://www.svsu.edu/' },
  { name: 'Saint Ambrose University', website: 'https://www.sau.edu/' },
  { name: 'Saint Anselm College', website: 'https://www.anselm.edu/' },
  { name: 'Saint Augustine’s University', website: 'https://www.st-aug.edu/' },
  { name: 'Saint Cloud State University', website: 'https://www.stcloudstate.edu/' },
  { name: 'Saint Edward’s University', website: 'https://www.stedwards.edu/' },
  { name: 'Saint Francis University', website: 'https://www.francis.edu/' },
  { name: 'Saint John Fisher University', website: 'https://www.sjf.edu/' },
  { name: 'Saint Joseph’s College', website: 'https://www.sjcme.edu/' },
  { name: 'Saint Joseph’s University', website: 'https://www.sju.edu/' },
  { name: 'Saint Louis University', website: 'https://www.slu.edu/' },
  { name: 'Saint Mary-of-the-Woods College', website: 'https://www.smwc.edu/' },
  { name: 'Saint Mary’s College', website: 'https://www.saintmarys.edu/' },
  { name: 'Saint Mary’s College of California', website: 'https://www.stmarys-ca.edu/' },
  { name: 'Saint Mary’s University of Minnesota', website: 'https://www.smumn.edu/' },
  { name: 'Saint Michael’s College', website: 'https://www.smcvt.edu/' },
  { name: 'Saint Norbert College', website: 'https://www.snc.edu/' },
  { name: 'Saint Olaf College', website: 'https://wp.stolaf.edu/' },
  { name: 'Saint Peter’s University', website: 'https://www.saintpeters.edu/' },
  { name: 'Saint Vincent College', website: 'https://www.stvincent.edu/' },
  { name: 'Salem College', website: 'https://www.salem.edu/' },
  { name: 'Salem State University', website: 'https://www.salemstate.edu/' },
  { name: 'Salisbury University', website: 'https://www.salisbury.edu/' },
  { name: 'Sam Houston State University', website: 'https://www.shsu.edu/' },
  { name: 'Samford University', website: 'https://www.samford.edu/' },
  { name: 'San Diego State University', website: 'https://www.sdsu.edu/' },
  { name: 'San Francisco State University', website: 'https://www.sfsu.edu/' },
  { name: 'San Jose State University', website: 'https://www.sjsu.edu/' },
  { name: 'Santa Clara University', website: 'https://www.scu.edu/' },
  { name: 'Sarah Lawrence College', website: 'https://www.sarahlawrence.edu/' },
  { name: 'Savannah College of Art and Design', website: 'https://www.scad.edu/' },
  { name: 'Savannah State University', website: 'https://www.savannahstate.edu/' },
  { name: 'School of the Art Institute of Chicago', website: 'https://www.saic.edu/' },
  { name: 'Scripps College', website: 'https://www.scrippscollege.edu/' },
  { name: 'Seattle Pacific University', website: 'https://spu.edu/' },
  { name: 'Seattle University', website: 'https://www.seattleu.edu/' },
  { name: 'Seton Hall University', website: 'https://www.shu.edu/' },
  { name: 'Seton Hill University', website: 'https://www.setonhill.edu/' },
  { name: 'Sewanee: The University of the South', website: 'https://new.sewanee.edu/' },
  { name: 'Shaw University', website: 'https://www.shawu.edu/' },
  { name: 'Shenandoah University', website: 'https://www.su.edu/' },
  { name: 'Shepherd University', website: 'https://www.shepherd.edu/' },
  { name: 'Shippensburg University', website: 'https://www.ship.edu/' },
  { name: 'Siena College', website: 'https://www.siena.edu/' },
  { name: 'Siena Heights University', website: 'https://www.sienaheights.edu/' },
  { name: 'Simmons University', website: 'https://www.simmons.edu/' },
  { name: 'Simpson College', website: 'https://simpson.edu/' },
  { name: 'Simpson University', website: 'https://simpsonu.edu/' },
  { name: 'Skidmore College', website: 'https://www.skidmore.edu/' },
  { name: 'Slippery Rock University', website: 'https://www.sru.edu/' },
  { name: 'Smith College', website: 'https://www.smith.edu/' },
  { name: 'Sonoma State University', website: 'https://www.sonoma.edu/' },
  { name: 'South Carolina State University', website: 'https://www.scsu.edu/' },
  { name: 'South Dakota School of Mines and Technology', website: 'https://www.sdsmt.edu/' },
  { name: 'South Dakota State University', website: 'https://www.sdstate.edu/' },
  { name: 'Southeast Missouri State University', website: 'https://semo.edu/' },
  { name: 'Southeastern Louisiana University', website: 'https://www.southeastern.edu/' },
  { name: 'Southeastern Oklahoma State University', website: 'https://www.se.edu/' },
  { name: 'Southern Adventist University', website: 'https://www.southern.edu/' },
  { name: 'Southern Arkansas University', website: 'https://web.saumag.edu/' },
  { name: 'Southern Connecticut State University', website: 'https://www.southernct.edu/' },
  { name: 'Southern Illinois University', website: 'https://siu.edu/' },
  { name: 'Southern Methodist University', website: 'https://www.smu.edu/' },
  { name: 'Southern Nazarene University', website: 'https://www.snu.edu/' },
  { name: 'Southern New Hampshire University', website: 'https://www.snhu.edu/' },
  { name: 'Southern Oregon University', website: 'https://sou.edu/' },
  { name: 'Southern Utah University', website: 'https://www.suu.edu/' },
  { name: 'Southern Vermont College', website: 'https://svc.edu/' },
  { name: 'Southern Wesleyan University', website: 'https://www.swu.edu/' },
  { name: 'Southwest Baptist University', website: 'https://www.sbuniv.edu/' },
  { name: 'Southwest Minnesota State University', website: 'https://www.smsu.edu/' },
  { name: 'Southwestern Adventist University', website: 'https://www.swau.edu/' },
  { name: 'Southwestern Assemblies of God University', website: 'https://www.sagu.edu/' },
  { name: 'Southwestern Christian University', website: 'https://swcu.edu/' },
  { name: 'Southwestern College', website: 'https://www.sckans.edu/' },
  { name: 'Southwestern Oklahoma State University', website: 'https://www.swosu.edu/' },
  { name: 'Southwestern University', website: 'https://www.southwestern.edu/' },
  { name: 'Spelman College', website: 'https://www.spelman.edu/' },
  { name: 'Spring Arbor University', website: 'https://www.arbor.edu/' },
  { name: 'Spring Hill College', website: 'https://www.shc.edu/' },
  { name: 'Springfield College', website: 'https://springfield.edu/' },
  { name: 'St. Bonaventure University', website: 'https://www.sbu.edu/' },
  { name: 'St. Catherine University', website: 'https://www.stkate.edu/' },
  { name: 'St. Edward’s University', website: 'https://www.stedwards.edu/' },
  { name: 'St. Francis College', website: 'https://www.sfc.edu/' },
  { name: 'St. John’s College', website: 'https://www.sjc.edu/' },
  { name: 'St. John’s University', website: 'https://www.stjohns.edu/' },
  { name: 'St. Lawrence University', website: 'https://www.stlawu.edu/' },
  { name: 'St. Louis College of Pharmacy', website: 'https://www.stlcop.edu/' },
  { name: 'St. Mary’s College of Maryland', website: 'https://www.smcm.edu/' },
  { name: 'St. Thomas Aquinas College', website: 'https://www.stac.edu/' },
  { name: 'St. Thomas University', website: 'https://www.stu.edu/' },
  { name: 'Stanford University', website: 'https://www.stanford.edu/' },
  { name: 'State University of New York', website: 'https://www.suny.edu/' },
  { name: 'Stephen F. Austin State University', website: 'https://www.sfasu.edu/' },
  { name: 'Stephens College', website: 'https://www.stephens.edu/' },
  { name: 'Stetson University', website: 'https://www.stetson.edu/' },
  { name: 'Stevens Institute of Technology', website: 'https://www.stevens.edu/' },
  { name: 'Stevenson University', website: 'https://www.stevenson.edu/' },
  { name: 'Stockton University', website: 'https://www.stockton.edu/' },
  { name: 'Stonehill College', website: 'https://www.stonehill.edu/' },
  { name: 'Stony Brook University', website: 'https://www.stonybrook.edu/' },
  { name: 'Suffolk University', website: 'https://www.suffolk.edu/' },
  { name: 'Sul Ross State University', website: 'https://www.sulross.edu/' },
  { name: 'Susquehanna University', website: 'https://www.susqu.edu/' },
  { name: 'Swarthmore College', website: 'https://www.swarthmore.edu/' },
  { name: 'Sweet Briar College', website: 'https://sbc.edu/' },
  { name: 'Syracuse University', website: 'https://www.syracuse.edu/' },
  { name: 'Tarleton State University', website: 'https://www.tarleton.edu/' },
  { name: 'Taylor University', website: 'https://www.taylor.edu/' },
  { name: 'Temple University', website: 'https://www.temple.edu/' },
  { name: 'Tennessee State University', website: 'https://www.tnstate.edu/' },
  { name: 'Tennessee Technological University', website: 'https://www.tntech.edu/' },
  { name: 'Tennessee Wesleyan University', website: 'https://www.tnwesleyan.edu/' },
  { name: 'Texas A&M University', website: 'https://www.tamu.edu/' },
  { name: 'Texas A&M University–Commerce', website: 'https://www.tamuc.edu/' },
  { name: 'Texas A&M University–Corpus Christi', website: 'https://www.tamucc.edu/' },
  { name: 'Texas A&M University–Kingsville', website: 'https://www.tamuk.edu/' },
  { name: 'Texas Christian University', website: 'https://www.tcu.edu/' },
  { name: 'Texas Lutheran University', website: 'https://www.tlu.edu/' },
  { name: 'Texas Southern University', website: 'https://www.tsu.edu/' },
  { name: 'Texas State University', website: 'https://www.txstate.edu/' },
  { name: 'Texas Tech University', website: 'https://www.ttu.edu/' },
  { name: 'Texas Wesleyan University', website: 'https://txwes.edu/' },
  { name: 'Texas Woman’s University', website: 'https://twu.edu/' },
  { name: 'The Citadel', website: 'https://www.citadel.edu/' },
  { name: 'The College of New Jersey', website: 'https://tcnj.edu/' },
  { name: 'The College of Saint Rose', website: 'https://www.strose.edu/' },
  { name: 'The College of Wooster', website: 'https://wooster.edu/' },
  { name: 'The George Washington University', website: 'https://www.gwu.edu/' },
  { name: 'The Juilliard School', website: 'https://www.juilliard.edu/' },
  { name: 'The New School', website: 'https://www.newschool.edu/' },
  { name: 'The Ohio State University', website: 'https://www.osu.edu/' },
  { name: 'The University of Alabama', website: 'https://www.ua.edu/' },
  { name: 'The University of Arizona', website: 'https://www.arizona.edu/' },
  { name: 'The University of Chicago', website: 'https://www.uchicago.edu/' },
  { name: 'The University of Mississippi', website: 'https://olemiss.edu/' },
  { name: 'The University of Tampa', website: 'https://www.ut.edu/' },
  { name: 'The University of Tennessee', website: 'https://www.utk.edu/' },
  { name: 'The University of Texas at Arlington', website: 'https://www.uta.edu/' },
  { name: 'The University of Texas at Austin', website: 'https://www.utexas.edu/' },
  { name: 'The University of Texas at Dallas', website: 'https://www.utdallas.edu/' },
  { name: 'The University of Texas at El Paso', website: 'https://www.utep.edu/' },
  { name: 'The University of Texas at San Antonio', website: 'https://www.utsa.edu/' },
  { name: 'The University of Texas Rio Grande Valley', website: 'https://www.utrgv.edu/' },
  { name: 'The University of the Arts', website: 'https://www.uarts.edu/' },
  { name: 'The University of Tulsa', website: 'https://utulsa.edu/' },
  { name: 'Thiel College', website: 'https://www.thiel.edu/' },
  { name: 'Thomas College', website: 'https://www.thomas.edu/' },
  { name: 'Thomas Jefferson University', website: 'https://www.jefferson.edu/' },
  { name: 'Thomas More University', website: 'https://www.thomasmore.edu/' },
  { name: 'Tiffin University', website: 'https://www.tiffin.edu/' },
  { name: 'Toccoa Falls College', website: 'https://tfc.edu/' },
  { name: 'Tougaloo College', website: 'https://www.tougaloo.edu/' },
  { name: 'Touro College', website: 'https://www.touro.edu/' },
  { name: 'Transylvania University', website: 'https://www.transy.edu/' },
  { name: 'Trine University', website: 'https://www.trine.edu/' },
  { name: 'Trinity Christian College', website: 'https://www.trnty.edu/' },
  { name: 'Trinity College', website: 'https://www.trincoll.edu/' },
  { name: 'Trinity University', website: 'https://www.trinity.edu/' },
  { name: 'Trinity Washington University', website: 'https://www.trinitydc.edu/' },
  { name: 'Troy University', website: 'https://www.troy.edu/' },
  { name: 'Truman State University', website: 'https://www.truman.edu/' },
  { name: 'Tufts University', website: 'https://www.tufts.edu/' },
  { name: 'Tulane University', website: 'https://tulane.edu/' },
 { name: 'Union College', website: 'https://www.union.edu/' },
  { name: 'Union University', website: 'https://www.uu.edu/' },
  { name: 'United States Air Force Academy', website: 'https://www.usafa.edu/' },
  { name: 'United States Coast Guard Academy', website: 'https://www.uscga.edu/' },
  { name: 'United States Merchant Marine Academy', website: 'https://www.usmma.edu/' },
  { name: 'United States Military Academy', website: 'https://www.westpoint.edu/' },
  { name: 'United States Naval Academy', website: 'https://www.usna.edu/' },
  { name: 'Unity College', website: 'https://www.unity.edu/' },
  { name: 'University at Albany, SUNY', website: 'https://www.albany.edu/' },
  { name: 'University at Buffalo, SUNY', website: 'https://www.buffalo.edu/' },
  { name: 'University of Akron', website: 'https://www.uakron.edu/' },
  { name: 'University of Alabama at Birmingham', website: 'https://www.uab.edu/' },
  { name: 'University of Alaska Anchorage', website: 'https://www.uaa.alaska.edu/' },
  { name: 'University of Alaska Fairbanks', website: 'https://www.uaf.edu/' },
  { name: 'University of Alaska Southeast', website: 'https://uas.alaska.edu/' },
  { name: 'University of Arkansas', website: 'https://www.uark.edu/' },
  { name: 'University of Arkansas at Little Rock', website: 'https://ualr.edu/' },
  { name: 'University of Arkansas at Monticello', website: 'https://www.uamont.edu/' },
  { name: 'University of Arkansas at Pine Bluff', website: 'https://www.uapb.edu/' },
  { name: 'University of Bridgeport', website: 'https://www.bridgeport.edu/' },
  { name: 'University of California, Berkeley', website: 'https://www.berkeley.edu/' },
  { name: 'University of California, Davis', website: 'https://www.ucdavis.edu/' },
  { name: 'University of California, Irvine', website: 'https://www.uci.edu/' },
  { name: 'University of California, Los Angeles (UCLA)', website: 'https://www.ucla.edu/' },
  { name: 'University of California, Merced', website: 'https://www.ucmerced.edu/' },
  { name: 'University of California, Riverside', website: 'https://www.ucr.edu/' },
  { name: 'University of California, San Diego (UCSD)', website: 'https://www.ucsd.edu/' },
  { name: 'University of California, San Francisco (UCSF)', website: 'https://www.ucsf.edu/' },
  { name: 'University of California, Santa Barbara (UCSB)', website: 'https://www.ucsb.edu/' },
  { name: 'University of California, Santa Cruz (UCSC)', website: 'https://www.ucsc.edu/' },
  { name: 'University of Central Arkansas', website: 'https://uca.edu/' },
  { name: 'University of Central Florida', website: 'https://www.ucf.edu/' },
  { name: 'University of Central Missouri', website: 'https://www.ucmo.edu/' },
  { name: 'University of Charleston', website: 'https://www.ucwv.edu/' },
  { name: 'University of Chicago', website: 'https://www.uchicago.edu/' },
  { name: 'University of Cincinnati', website: 'https://www.uc.edu/' },
  { name: 'University of Colorado Boulder', website: 'https://www.colorado.edu/' },
  { name: 'University of Colorado Colorado Springs', website: 'https://www.uccs.edu/' },
  { name: 'University of Colorado Denver', website: 'https://www.ucdenver.edu/' },
  { name: 'University of Connecticut', website: 'https://www.uconn.edu/' },
  { name: 'University of Dallas', website: 'https://udallas.edu/' },
  { name: 'University of Dayton', website: 'https://udayton.edu/' },
  { name: 'University of Delaware', website: 'https://www.udel.edu/' },
  { name: 'University of Denver', website: 'https://www.du.edu/' },
  { name: 'University of Detroit Mercy', website: 'https://www.udmercy.edu/' },
  { name: 'University of Evansville', website: 'https://www.evansville.edu/' },
  { name: 'University of Florida', website: 'https://www.ufl.edu/' },
  { name: 'University of Georgia', website: 'https://www.uga.edu/' },
  { name: 'University of Hartford', website: 'https://www.hartford.edu/' },
  { name: 'University of Hawaii at Hilo', website: 'https://hilo.hawaii.edu/' },
  { name: 'University of Hawaii at Manoa', website: 'https://manoa.hawaii.edu/' },
  { name: 'University of Houston', website: 'https://www.uh.edu/' },
  { name: 'University of Idaho', website: 'https://www.uidaho.edu/' },
  { name: 'University of Illinois Chicago (UIC)', website: 'https://www.uic.edu/' },
  { name: 'University of Illinois Springfield', website: 'https://www.uis.edu/' },
  { name: 'University of Illinois Urbana-Champaign', website: 'https://www.uillinois.edu/' },
  { name: 'University of Indianapolis', website: 'https://uindy.edu/' },
  { name: 'University of Iowa', website: 'https://uiowa.edu/' },
  { name: 'University of Kansas', website: 'https://www.ku.edu/' },
  { name: 'University of Kentucky', website: 'https://www.uky.edu/' },
  { name: 'University of La Verne', website: 'https://laverne.edu/' },
  { name: 'University of Louisiana at Lafayette', website: 'https://www.louisiana.edu/' },
  { name: 'University of Louisiana at Monroe', website: 'https://www.ulm.edu/' },
  { name: 'University of Louisville', website: 'https://louisville.edu/' },
  { name: 'University of Maine', website: 'https://umaine.edu/' },
  { name: 'University of Mary', website: 'https://www.umary.edu/' },
  { name: 'University of Mary Hardin-Baylor', website: 'https://www.umhb.edu/' },
  { name: 'University of Maryland, Baltimore', website: 'https://www.umaryland.edu/' },
  { name: 'University of Maryland, Baltimore County (UMBC)', website: 'https://umbc.edu/' },
  { name: 'University of Maryland, College Park', website: 'https://umd.edu/' },
  { name: 'University of Massachusetts Amherst', website: 'https://www.umass.edu/' },
  { name: 'University of Massachusetts Boston', website: 'https://www.umb.edu/' },
  { name: 'University of Massachusetts Dartmouth', website: 'https://www.umassd.edu/' },
  { name: 'University of Massachusetts Lowell', website: 'https://www.uml.edu/' },
  { name: 'University of Memphis', website: 'https://www.memphis.edu/' },
  { name: 'University of Miami', website: 'https://welcome.miami.edu/' },
  { name: 'University of Michigan', website: 'https://umich.edu/' },
  { name: 'University of Minnesota', website: 'https://www.umn.edu/' },
  { name: 'University of Mississippi', website: 'https://olemiss.edu/' },
  { name: 'University of Missouri', website: 'https://missouri.edu/' },
  { name: 'University of Montana', website: 'https://www.umt.edu/' },
  { name: 'University of Nebraska at Kearney', website: 'https://www.unk.edu/' },
  { name: 'University of Nebraska at Omaha', website: 'https://www.unomaha.edu/' },
  { name: 'University of Nebraska–Lincoln', website: 'https://www.unl.edu/' },
  { name: 'University of Nevada, Las Vegas', website: 'https://www.unlv.edu/' },
  { name: 'University of Nevada, Reno', website: 'https://www.unr.edu/' },
  { name: 'University of New England', website: 'https://www.une.edu/' },
  { name: 'University of New Hampshire', website: 'https://www.unh.edu/' },
  { name: 'University of New Haven', website: 'https://www.newhaven.edu/' },
  { name: 'University of New Mexico', website: 'https://www.unm.edu/' },
  { name: 'University of New Orleans', website: 'https://www.uno.edu/' },
  { name: 'University of North Alabama', website: 'https://www.una.edu/' },
  { name: 'University of North Carolina at Chapel Hill', website: 'https://www.unc.edu/' },
  { name: 'University of North Carolina at Charlotte', website: 'https://www.charlotte.edu/' },
  { name: 'University of North Carolina at Greensboro', website: 'https://www.uncg.edu/' },
  { name: 'University of North Dakota', website: 'https://und.edu/' },
  { name: 'University of North Florida', website: 'https://www.unf.edu/' },
  { name: 'University of North Georgia', website: 'https://ung.edu/' },
  { name: 'University of North Texas', website: 'https://www.unt.edu/' },
  { name: 'University of Northern Colorado', website: 'https://www.unco.edu/' },
  { name: 'University of Northern Iowa', website: 'https://uni.edu/' },
  { name: 'University of Northwestern – St. Paul', website: 'https://unwsp.edu/' },
  { name: 'University of Notre Dame', website: 'https://www.nd.edu/' },
  { name: 'University of Oklahoma', website: 'https://www.ou.edu/' },
  { name: 'University of Oregon', website: 'https://uoregon.edu/' },
  { name: 'University of Pennsylvania', website: 'https://www.upenn.edu/' },
  { name: 'University of Pittsburgh', website: 'https://www.pitt.edu/' },
  { name: 'University of Portland', website: 'https://www.up.edu/' },
  { name: 'University of Puget Sound', website: 'https://www.pugetsound.edu/' },
  { name: 'University of Redlands', website: 'https://www.redlands.edu/' },
  { name: 'University of Rhode Island', website: 'https://web.uri.edu/' },
  { name: 'University of Richmond', website: 'https://www.richmond.edu/' },
  { name: 'University of Rochester', website: 'https://www.rochester.edu/' },
  { name: 'University of San Diego', website: 'https://www.sandiego.edu/' },
  { name: 'University of San Francisco', website: 'https://www.usfca.edu/' },
  { name: 'University of South Alabama', website: 'https://www.southalabama.edu/' },
  { name: 'University of South Carolina', website: 'https://sc.edu/' },
  { name: 'University of South Dakota', website: 'https://www.usd.edu/' },
  { name: 'University of South Florida', website: 'https://www.usf.edu/' },
  { name: 'University of Southern California (USC)', website: 'https://www.usc.edu/' },
  { name: 'University of Southern Maine', website: 'https://usm.maine.edu/' },
  { name: 'University of Southern Mississippi', website: 'https://www.usm.edu/' },
  { name: 'University of St. Francis', website: 'https://www.stfrancis.edu/' },
  { name: 'University of St. Thomas', website: 'https://www.stthomas.edu/' },
  { name: 'University of the Pacific', website: 'https://www.pacific.edu/' },
  { name: 'University of the South', website: 'https://new.sewanee.edu/' },
  { name: 'University of Toledo', website: 'https://www.utoledo.edu/' },
  { name: 'University of Tulsa', website: 'https://utulsa.edu/' },
  { name: 'University of Utah', website: 'https://www.utah.edu/' },
  { name: 'University of Vermont', website: 'https://www.uvm.edu/' },
  { name: 'University of Virginia', website: 'https://www.virginia.edu/' },
  { name: 'University of Washington', website: 'https://www.washington.edu/' },
  { name: 'University of West Alabama', website: 'https://www.uwa.edu/' },
  { name: 'University of West Florida', website: 'https://uwf.edu/' },
  { name: 'University of West Georgia', website: 'https://www.westga.edu/' },
  { name: 'University of Wisconsin-Madison', website: 'https://www.wisc.edu/' },
  { name: 'University of Wyoming', website: 'https://www.uwyo.edu/' },
  { name: 'Ursinus College', website: 'https://www.ursinus.edu/' },
  { name: 'Utah State University', website: 'https://www.usu.edu/' },
  { name: 'Utica University', website: 'https://www.utica.edu/' },
  { name: 'Valdosta State University', website: 'https://www.valdosta.edu/' },
  { name: 'Valparaiso University', website: 'https://www.valpo.edu/' },
  { name: 'Vanderbilt University', website: 'https://www.vanderbilt.edu/' },
  { name: 'Vassar College', website: 'https://www.vassar.edu/' },
  { name: 'Villanova University', website: 'https://www1.villanova.edu/' },
  { name: 'Virginia Commonwealth University', website: 'https://www.vcu.edu/' },
  { name: 'Virginia Military Institute', website: 'https://www.vmi.edu/' },
  { name: 'Virginia State University', website: 'https://www.vsu.edu/' },
  { name: 'Virginia Tech', website: 'https://www.vt.edu/' },
  { name: 'Virginia Union University', website: 'https://www.vuu.edu/' },
  { name: 'Virginia Wesleyan University', website: 'https://www.vwu.edu/' },
  { name: 'Wabash College', website: 'https://www.wabash.edu/' },
  { name: 'Wagner College', website: 'https://wagner.edu/' },
  { name: 'Wake Forest University', website: 'https://www.wfu.edu/' },
  { name: 'Walla Walla University', website: 'https://www.wallawalla.edu/' },
  { name: 'Warren Wilson College', website: 'https://www.warren-wilson.edu/' },
  { name: 'Wartburg College', website: 'https://www.wartburg.edu/' },
  { name: 'Washington & Jefferson College', website: 'https://www.washjeff.edu/' },
  { name: 'Washington and Lee University', website: 'https://www.wlu.edu/' },
  { name: 'Washington College', website: 'https://www.washcoll.edu/' },
  { name: 'Washington State University', website: 'https://wsu.edu/' },
  { name: 'Washington University in St. Louis', website: 'https://wustl.edu/' },
  { name: 'Wayland Baptist University', website: 'https://www.wbu.edu/' },
  { name: 'Wayne State College', website: 'https://www.wsc.edu/' },
  { name: 'Wayne State University', website: 'https://wayne.edu/' },
  { name: 'Webb Institute', website: 'https://www.webb.edu/' },
  { name: 'Weber State University', website: 'https://www.weber.edu/' },
  { name: 'Wellesley College', website: 'https://www.wellesley.edu/' },
  { name: 'Wells College', website: 'https://www.wells.edu/' },
  { name: 'Wentworth Institute of Technology', website: 'https://wit.edu/' },
  { name: 'Wesleyan College', website: 'https://www.wesleyancollege.edu/' },
  { name: 'Wesleyan University', website: 'https://www.wesleyan.edu/' },
  { name: 'West Chester University', website: 'https://www.wcupa.edu/' },
  { name: 'West Liberty University', website: 'https://westliberty.edu/' },
  { name: 'West Texas A&M University', website: 'https://www.wtamu.edu/' },
  { name: 'West Virginia State University', website: 'https://www.wvstateu.edu/' },
  { name: 'West Virginia University', website: 'https://www.wvu.edu/' },
  { name: 'Western Carolina University', website: 'https://www.wcu.edu/' },
  { name: 'Western Colorado University', website: 'https://www.western.edu/' },
  { name: 'Western Connecticut State University', website: 'https://www.wcsu.edu/' },
  { name: 'Western Illinois University', website: 'https://www.wiu.edu/' },
  { name: 'Western Kentucky University', website: 'https://www.wku.edu/' },
  { name: 'Western Michigan University', website: 'https://wmich.edu/' },
  { name: 'Western New England University', website: 'https://www.wne.edu/' },
  { name: 'Western Oregon University', website: 'https://wou.edu/' },
  { name: 'Western Washington University', website: 'https://www.wwu.edu/' },
  { name: 'Westfield State University', website: 'https://www.westfield.ma.edu/' },
  { name: 'Westminster College', website: 'https://www.westminster.edu/' },
  { name: 'Westmont College', website: 'https://www.westmont.edu/' },
  { name: 'Wheaton College', website: 'https://www.wheaton.edu/' },
  { name: 'Wheeling University', website: 'https://wheeling.edu/' },
  { name: 'Whitman College', website: 'https://www.whitman.edu/' },
  { name: 'Whittier College', website: 'https://www.whittier.edu/' },
  { name: 'Whitworth University', website: 'https://www.whitworth.edu/' },
  { name: 'Wichita State University', website: 'https://www.wichita.edu/' },
  { name: 'Widener University', website: 'https://www.widener.edu/' },
  { name: 'Wilberforce University', website: 'https://wilberforce.edu/' },
  { name: 'Wiley College', website: 'https://www.wileyc.edu/' },
  { name: 'Wilkes University', website: 'https://www.wilkes.edu/' },
  { name: 'Willamette University', website: 'https://willamette.edu/' },
  { name: 'William Carey University', website: 'https://www.wmcarey.edu/' },
  { name: 'William Jewell College', website: 'https://www.jewell.edu/' },
  { name: 'William Paterson University', website: 'https://www.wpunj.edu/' },
  { name: 'William Penn University', website: 'https://www.wmpenn.edu/' },
  { name: 'William Woods University', website: 'https://www.williamwoods.edu/' },
  { name: 'Williams College', website: 'https://www.williams.edu/' },
  { name: 'Wilmington University', website: 'https://www.wilmu.edu/' },
  { name: 'Wilson College', website: 'https://www.wilson.edu/' },
  { name: 'Wingate University', website: 'https://www.wingate.edu/' },
  { name: 'Winona State University', website: 'https://www.winona.edu/' },
  { name: 'Winthrop University', website: 'https://www.winthrop.edu/' },
  { name: 'Wisconsin Lutheran College', website: 'https://www.wlc.edu/' },
  { name: 'Wittenberg University', website: 'https://www.wittenberg.edu/' },
  { name: 'Wofford College', website: 'https://www.wofford.edu/' },
  { name: 'Woodbury University', website: 'https://woodbury.edu/' },
  { name: 'Worcester Polytechnic Institute', website: 'https://www.wpi.edu/' },
  { name: 'Worcester State University', website: 'https://www.worcester.edu/' },
  { name: 'Wright State University', website: 'https://www.wright.edu/' },
  { name: 'Xavier University', website: 'https://www.xavier.edu/' },
  { name: 'Xavier University of Louisiana', website: 'https://www.xula.edu/' },
  { name: 'Yale University', website: 'https://www.yale.edu/' },
  { name: 'Yeshiva University', website: 'https://www.yu.edu/' },
  { name: 'York College of Pennsylvania', website: 'https://www.ycp.edu/' },
  { name: 'Youngstown State University', website: 'https://ysu.edu/' },
 


  ],
  'canada': [
     { name: 'Acadia University', website: 'https://www.acadiau.ca/' },
    { name: 'Algonquin College', website: 'https://www.algonquincollege.com/' },
    { name: 'Bow Valley College', website: 'https://bowvalleycollege.ca/' },
    { name: 'Brock University', website: 'https://www.brocku.ca/' },
    { name: 'British Columbia Institute of Technology (BCIT)', website: 'https://www.bcit.ca/' },
    { name: 'Carleton University', website: 'https://www.carleton.ca/' },
    { name: 'Centennial College', website: 'https://www.centennialcollege.ca/' },
    { name: 'Collège Ahuntsic', website: 'https://www.collegeahuntsic.qc.ca/' },
    { name: 'Collège de Maisonneuve', website: 'https://www.cmaisonneuve.qc.ca/' },
    { name: 'Concordia University', website: 'https://www.concordia.ca/' },
    { name: 'Conestoga College', website: 'https://www.conestogac.on.ca/' },
    { name: 'Dalhousie University', website: 'https://www.dal.ca/' },
    { name: 'George Brown College', website: 'https://www.georgebrown.ca/' },
    { name: 'Humber College', website: 'https://www.humber.ca/' },
    { name: 'Lambton College', website: 'https://www.lambtoncollege.ca/' },
    { name: 'Langara College', website: 'https://langara.ca/' },
    { name: 'McGill University', website: 'https://www.mcgill.ca/' },
    { name: 'McMaster University', website: 'https://www.mcmaster.ca/' },
    { name: 'Macewan University', website: 'https://www.macewan.ca/' },
    { name: 'Mohawk College', website: 'https://www.mohawkcollege.ca/' },
    { name: 'Mount Royal University', website: 'https://www.mtroyal.ca/' },
    { name: 'Okanagan College', website: 'https://www.okanagan.bc.ca/' },
    { name: 'Queen\'s University', website: 'https://www.queensu.ca/' },
    { name: 'Red River College', website: 'https://www.rrc.ca/' },
    { name: 'Ryerson University', website: 'https://www.ryerson.ca/' },
    { name: 'Seneca College', website: 'https://www.senecacollege.ca/' },
    { name: 'Sheridan College', website: 'https://www.sheridancollege.ca/' },
    { name: 'Sherbrooke College', website: 'https://www.cegepsherbrooke.qc.ca/' },
    { name: 'Simon Fraser University', website: 'https://www.sfu.ca/' },
    { name: 'St. Clair College', website: 'https://www.stclaircollege.ca/' },
    { name: 'St. Francis Xavier University', website: 'https://www.stfx.ca/' },
    { name: 'St. Lawrence College', website: 'https://www.stlawrencecollege.ca/' },
    { name: 'Tyndale University', website: 'https://www.tyndale.ca/' },
    { name: 'Université de Montréal', website: 'https://www.umontreal.ca/' },
    { name: 'Université Laval', website: 'https://www.ulaval.ca/' },
    { name: 'Université de Sherbrooke', website: 'https://www.usherbrooke.ca/' },
    { name: 'University of Alberta', website: 'https://www.ualberta.ca/' },
    { name: 'University of British Columbia', website: 'https://www.ubc.ca/' },
    { name: 'University of Calgary', website: 'https://www.ucalgary.ca/' },
    { name: 'University of Guelph', website: 'https://www.uoguelph.ca/' },
    { name: 'University of Manitoba', website: 'https://umanitoba.ca/' },
    { name: 'University of Ottawa', website: 'https://www.uottawa.ca/' },
    { name: 'University of Saskatchewan', website: 'https://www.usask.ca/' },
    { name: 'University of Toronto', website: 'https://www.utoronto.ca/' },
    { name: 'University of Victoria', website: 'https://www.uvic.ca/' },
    { name: 'University of Waterloo', website: 'https://uwaterloo.ca/' },
    { name: 'University of Western Ontario', website: 'https://www.uwo.ca/' },
    { name: 'Vancouver Community College', website: 'https://www.vcc.ca/' },
    { name: 'Vancouver Island University', website: 'https://www.viu.ca/' },
    { name: 'Wilfrid Laurier University', website: 'https://www.wlu.ca/' },
    { name: 'York University', website: 'https://www.yorku.ca/' },
  ],
  'australia': [
    { name: 'Australian Catholic University', website: 'https://www.acu.edu.au/' },
    { name: 'Australian National University', website: 'https://www.anu.edu.au/' },
    { name: 'Bond University', website: 'https://www.bond.edu.au/' },
    { name: 'Curtin University', website: 'https://www.curtin.edu.au/' },
    { name: 'Deakin University', website: 'https://www.deakin.edu.au/' },
    { name: 'Griffith University', website: 'https://www.griffith.edu.au/' },
    { name: 'La Trobe University', website: 'https://www.latrobe.edu.au/' },
    { name: 'Monash University', website: 'https://www.monash.edu/' },
    { name: 'Murdoch University', website: 'https://www.murdoch.edu.au/' },
    { name: 'TAFE Queensland', website: 'https://tafeqld.edu.au/' },
    { name: 'University of Adelaide', website: 'https://www.adelaide.edu.au/' },
    { name: 'University of Melbourne', website: 'https://www.unimelb.edu.au/' },
    { name: 'University of New South Wales', website: 'https://www.unsw.edu.au/' },
    { name: 'University of Newcastle', website: 'https://www.newcastle.edu.au/' },
    { name: 'University of Queensland', website: 'https://www.uq.edu.au/' },
    { name: 'University of South Australia', website: 'https://www.unisa.edu.au/' },
    { name: 'University of Sydney', website: 'https://www.sydney.edu.au/' },
    { name: 'University of Tasmania', website: 'https://www.utas.edu.au/' },
    { name: 'University of Technology Sydney', website: 'https://www.uts.edu.au/' },
    { name: 'University of Western Australia', website: 'https://www.uwa.edu.au/' },
    { name: 'University of Wollongong', website: 'https://www.uow.edu.au/' },
    { name: 'Victoria University', website: 'https://www.vu.edu.au/' },
    { name: 'Western Sydney University', website: 'https://www.westernsydney.edu.au/' },
  ],
  'new-zealand': [
     { name: 'Ara Institute of Canterbury', website: 'https://www.ara.ac.nz/' },
    { name: 'Auckland University of Technology (AUT)', website: 'https://www.aut.ac.nz/' },
    { name: 'Eastern Institute of Technology (EIT)', website: 'https://www.eit.ac.nz/' },
    { name: 'Lincoln University', website: 'https://www.lincoln.ac.nz/' },
    { name: 'Manukau Institute of Technology', website: 'https://www.manukau.ac.nz/' },
    { name: 'Massey University', website: 'https://www.massey.ac.nz/' },
    { name: 'NorthTec', website: 'https://www.northtec.ac.nz/' },
    { name: 'Southern Institute of Technology (SIT)', website: 'https://www.sit.ac.nz/' },
    { name: 'Toi Ohomai Institute of Technology', website: 'https://www.toiohomai.ac.nz/' },
    { name: 'Unitec Institute of Technology', website: 'https://www.unitec.ac.nz/' },
    { name: 'University of Auckland', website: 'https://www.auckland.ac.nz/' },
    { name: 'University of Canterbury', website: 'https://www.canterbury.ac.nz/' },
    { name: 'University of Otago', website: 'https://www.otago.ac.nz/' },
    { name: 'University of Waikato', website: 'https://www.waikato.ac.nz/' },
    { name: 'Victoria University of Wellington', website: 'https://www.wgtn.ac.nz/' },
    { name: 'Wellington Institute of Technology (WelTec)', website: 'https://www.weltec.ac.nz/' },
    { name: 'Western Institute of Technology at Taranaki (WITT)', website: 'https://www.witt.ac.nz/' },
    { name: 'Whitireia New Zealand', website: 'https://www.whitireia.ac.nz/' },
  ],
  'ireland': [
    { name: 'Atlantic Technological University (ATU)', website: 'https://www.atu.ie/' },
    { name: 'Dublin Business School', website: 'https://www.dbs.ie/' },
    { name: 'Dublin City University (DCU)', website: 'https://www.dcu.ie/' },
    { name: 'Dublin Institute of Technology (DIT)', website: 'https://www.dit.ie/' },
    { name: 'Mary Immaculate College', website: 'https://www.mic.ul.ie/' },
    { name: 'Munster Technological University (MTU)', website: 'https://www.mtu.ie/' },
    { name: 'National College of Art and Design (NCAD)', website: 'https://www.ncad.ie/' },
    { name: 'National College of Ireland (NCI)', website: 'https://www.ncirl.ie/' },
    { name: 'National University of Ireland Galway (NUI Galway)', website: 'https://www.universityofgalway.ie/' },
    { name: 'Royal College of Surgeons in Ireland (RCSI)', website: 'https://www.rcsi.com/' },
    { name: 'South East Technological University (SETU)', website: 'https://www.setu.ie/' },
    { name: 'Technological University Dublin (TU Dublin)', website: 'https://www.tudublin.ie/' },
    { name: 'Technological University of the Shannon (TUS)', website: 'https://www.tus.ie/' },
    { name: 'Trinity College Dublin (TCD)', website: 'https://www.tcd.ie/' },
    { name: 'University College Cork (UCC)', website: 'https://www.ucc.ie/' },
    { name: 'University College Dublin (UCD)', website: 'https://www.ucd.ie/' },
    { name: 'University of Limerick (UL)', website: 'https://www.ul.ie/' },
  ],
};

const UniversityList = () => {
  const { country } = useParams<{ country: string }>();
  const [searchTerm, setSearchTerm] = useState('');
  const [filteredUniversities, setFilteredUniversities] = useState<University[]>([]);

  useEffect(() => {
    if (country && universities[country]) {
      const sorted = [...universities[country]].sort((a, b) => 
        a.name.localeCompare(b.name)
      );
      setFilteredUniversities(sorted);
    }
  }, [country]);

  const handleSearch = (event: React.ChangeEvent<HTMLInputElement>) => {
    const term = event.target.value.toLowerCase();
    setSearchTerm(term);
    
    if (country && universities[country]) {
      const filtered = universities[country].filter(uni => 
        uni.name.toLowerCase().includes(term)
      ).sort((a, b) => a.name.localeCompare(b.name));
      
      setFilteredUniversities(filtered);
    }
  };

  return (
    <div className="min-h-screen pt-24 pb-20 bg-gradient-to-b from-blue-50 via-white to-gray-50">
      <div className="container mx-auto px-4">
        <h1 className="text-3xl md:text-4xl font-bold text-center mb-8 text-gray-900">
          Universities in {country?.split('-').map(word => 
            word.charAt(0).toUpperCase() + word.slice(1)
          ).join(' ')}
        </h1>

        <div className="max-w-xl mx-auto mb-8">
          <div className="relative">
            <input
              type="text"
              placeholder="Search universities..."
              value={searchTerm}
              onChange={handleSearch}
              className="w-full px-6 py-4 rounded-xl border-2 border-blue-100 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm bg-white/80 backdrop-blur-sm"
            />
            <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
          </div>
        </div>

        <div className="grid gap-4 max-w-3xl mx-auto">
          {filteredUniversities.map((university, index) => (
            <a
              key={index}
              href={university.website}
              target="_blank"
              rel="noopener noreferrer"
              className="group bg-white p-6 rounded-xl shadow-sm border-2 border-blue-50 hover:border-blue-500 hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1"
            >
              <div className="flex justify-between items-center">
                <h2 className="text-xl font-semibold text-gray-900 group-hover:text-blue-600 transition-colors">
                  {university.name}
                </h2>
                <span className="text-blue-500 group-hover:translate-x-1 transition-transform duration-300">
                  →
                </span>
              </div>
              <p className="text-blue-600 mt-2 text-sm">Click to visit official website</p>
            </a>
          ))}
        </div>

        {filteredUniversities.length === 0 && (
          <div className="text-center text-gray-600 mt-8 bg-white p-8 rounded-xl shadow-sm border-2 border-blue-50">
            <p className="text-xl">No universities found matching your search.</p>
            <p className="mt-2">Try adjusting your search terms.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default UniversityList;